export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const AUTH_STOP_LOADING = 'AUTH_STOP_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const AUTH_ADD_FAVE = 'AUTH_ADD_FAVE';
export const AUTH_REMOVE_FAVE = 'AUTH_REMOVE_FAVE';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const SET_LOCATIONS_LOADING = 'SET_LOCATIONS_LOADING';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const ADD_FAVE = 'ADD_FAVE';
export const GET_FAVES = 'GET_FAVES';
export const REMOVE_FAVE = 'REMOVE_FAVE';
export const SET_FAVES = 'SET_FAVES';
export const SET_JC_CONTRACTS = 'SET_JC_CONTRACTS';

export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const SET_USER_LOCATION_LOADING = 'SET_USER_LOCATION_LOADING';

export const SET_MAP_ZOOM = 'SET_MAP_ZOOM';
export const SET_MAP_POSITION = 'SET_MAP_POSITION';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS';

export const STOP_LOADING = 'STOP_LOADING';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

// export const SETTINGS_SET_LOW_COLOR = 'SETTINGS_SET_LOW_COLOR';
// export const SETTINGS_SET_GOOD_COLOR = 'SETTINGS_SET_GOOD_COLOR';
export const SETTINGS_DEFAULT_COLORS = 'SETTINGS_DEFAULT_COLORS';
export const SETTINGS_UPDATE_COLORS = 'SETTINGS_UPDATE_COLORS';
export const SETTINGS_UPDATE_JC_CONTRACT = 'SETTINGS_UPDATE_JC_CONTRACT';

export const TUTORIAL_START = 'TUTORIAL_START';
export const TUTORIAL_VIEWED = 'TUTORIAL_VIEWED';
export const CHECK_TUTORIAL_VIEWED = 'CHECK_TUTORIAL_VIEWED';
